/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface InquiryInput {
    name: string;
    productId?: ProductId;
    message: string;
    phone: string;
}
export interface ProductInput {
    stockQuantity: bigint;
    name: string;
    description: string;
    imageUrl: string;
    category: string;
    price: number;
}
export type InquiryId = bigint;
export interface Inquiry {
    id: InquiryId;
    name: string;
    productId?: ProductId;
    isRead: boolean;
    message: string;
    timestamp: bigint;
    phone: string;
}
export interface IncomeStats {
    todayIncome: number;
    totalIncome: number;
    monthlyIncome: number;
}
export interface SaleInput {
    customerName?: string;
    productId: ProductId;
    quantity: bigint;
    phone?: string;
}
export type SaleId = bigint;
export interface Sale {
    id: SaleId;
    customerName?: string;
    productId: ProductId;
    productName: string;
    pricePerUnit: number;
    totalAmount: number;
    quantity: bigint;
    phone?: string;
    saleDate: bigint;
}
export type ProductId = bigint;
export interface UserProfile {
    name: string;
}
export interface Product {
    id: ProductId;
    status: ProductStatus;
    stockQuantity: bigint;
    name: string;
    description: string;
    imageUrl: string;
    isHidden: boolean;
    category: string;
    price: number;
}
export enum ProductStatus {
    inStock = "inStock",
    outOfStock = "outOfStock"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createProduct(product: ProductInput): Promise<ProductId>;
    deleteInquiry(id: InquiryId): Promise<void>;
    deleteProduct(id: ProductId): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getIncomeStats(): Promise<IncomeStats>;
    getInquiries(): Promise<Array<Inquiry>>;
    getLowStockProducts(): Promise<Array<Product>>;
    getMonthlyIncome(): Promise<number>;
    getProductById(id: ProductId): Promise<Product | null>;
    getProducts(hideOutOfStock: boolean): Promise<Array<Product>>;
    getSalesByDate(dayTimestamp: bigint): Promise<Array<Sale>>;
    getSalesByMonth(year: bigint, month: bigint): Promise<Array<Sale>>;
    getSalesByProduct(productId: ProductId): Promise<Array<Sale>>;
    getTodayIncome(): Promise<number>;
    getTotalIncome(): Promise<number>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markInquiryRead(id: InquiryId): Promise<void>;
    recordSale(input: SaleInput): Promise<SaleId>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setLowStockThreshold(newThreshold: bigint): Promise<void>;
    submitInquiry(input: InquiryInput): Promise<InquiryId>;
    updateProduct(id: ProductId, product: ProductInput): Promise<void>;
}
import type { Inquiry as _Inquiry, InquiryId as _InquiryId, InquiryInput as _InquiryInput, Product as _Product, ProductId as _ProductId, ProductStatus as _ProductStatus, Sale as _Sale, SaleId as _SaleId, SaleInput as _SaleInput, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createProduct(arg0: ProductInput): Promise<ProductId> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(arg0);
            return result;
        }
    }
    async deleteInquiry(arg0: InquiryId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInquiry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInquiry(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: ProductId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIncomeStats(): Promise<IncomeStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncomeStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncomeStats();
            return result;
        }
    }
    async getInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInquiries();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInquiries();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLowStockProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowStockProducts();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowStockProducts();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlyIncome(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyIncome();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyIncome();
            return result;
        }
    }
    async getProductById(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductById(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductById(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(arg0: boolean): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSalesByDate(arg0: bigint): Promise<Array<Sale>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesByDate(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesByDate(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSalesByMonth(arg0: bigint, arg1: bigint): Promise<Array<Sale>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesByMonth(arg0, arg1);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesByMonth(arg0, arg1);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSalesByProduct(arg0: ProductId): Promise<Array<Sale>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesByProduct(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesByProduct(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodayIncome(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodayIncome();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodayIncome();
            return result;
        }
    }
    async getTotalIncome(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalIncome();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalIncome();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markInquiryRead(arg0: InquiryId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markInquiryRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markInquiryRead(arg0);
            return result;
        }
    }
    async recordSale(arg0: SaleInput): Promise<SaleId> {
        if (this.processError) {
            try {
                const result = await this.actor.recordSale(to_candid_SaleInput_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordSale(to_candid_SaleInput_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setLowStockThreshold(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLowStockThreshold(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLowStockThreshold(arg0);
            return result;
        }
    }
    async submitInquiry(arg0: InquiryInput): Promise<InquiryId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(to_candid_InquiryInput_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(to_candid_InquiryInput_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateProduct(arg0: ProductId, arg1: ProductInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Inquiry_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Inquiry): Inquiry {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ProductStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductStatus): ProductStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Sale_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sale): Sale {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProductId]): ProductId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    status: _ProductStatus;
    stockQuantity: bigint;
    name: string;
    description: string;
    imageUrl: string;
    isHidden: boolean;
    category: string;
    price: number;
}): {
    id: ProductId;
    status: ProductStatus;
    stockQuantity: bigint;
    name: string;
    description: string;
    imageUrl: string;
    isHidden: boolean;
    category: string;
    price: number;
} {
    return {
        id: value.id,
        status: from_candid_ProductStatus_n13(_uploadFile, _downloadFile, value.status),
        stockQuantity: value.stockQuantity,
        name: value.name,
        description: value.description,
        imageUrl: value.imageUrl,
        isHidden: value.isHidden,
        category: value.category,
        price: value.price
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SaleId;
    customerName: [] | [string];
    productId: _ProductId;
    productName: string;
    pricePerUnit: number;
    totalAmount: number;
    quantity: bigint;
    phone: [] | [string];
    saleDate: bigint;
}): {
    id: SaleId;
    customerName?: string;
    productId: ProductId;
    productName: string;
    pricePerUnit: number;
    totalAmount: number;
    quantity: bigint;
    phone?: string;
    saleDate: bigint;
} {
    return {
        id: value.id,
        customerName: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.customerName)),
        productId: value.productId,
        productName: value.productName,
        pricePerUnit: value.pricePerUnit,
        totalAmount: value.totalAmount,
        quantity: value.quantity,
        phone: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.phone)),
        saleDate: value.saleDate
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _InquiryId;
    name: string;
    productId: [] | [_ProductId];
    isRead: boolean;
    message: string;
    timestamp: bigint;
    phone: string;
}): {
    id: InquiryId;
    name: string;
    productId?: ProductId;
    isRead: boolean;
    message: string;
    timestamp: bigint;
    phone: string;
} {
    return {
        id: value.id,
        name: value.name,
        productId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.productId)),
        isRead: value.isRead,
        message: value.message,
        timestamp: value.timestamp,
        phone: value.phone
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inStock: null;
} | {
    outOfStock: null;
}): ProductStatus {
    return "inStock" in value ? ProductStatus.inStock : "outOfStock" in value ? ProductStatus.outOfStock : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Sale>): Array<Sale> {
    return value.map((x)=>from_candid_Sale_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Inquiry>): Array<Inquiry> {
    return value.map((x)=>from_candid_Inquiry_n7(_uploadFile, _downloadFile, x));
}
function to_candid_InquiryInput_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryInput): _InquiryInput {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_SaleInput_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SaleInput): _SaleInput {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName?: string;
    productId: ProductId;
    quantity: bigint;
    phone?: string;
}): {
    customerName: [] | [string];
    productId: _ProductId;
    quantity: bigint;
    phone: [] | [string];
} {
    return {
        customerName: value.customerName ? candid_some(value.customerName) : candid_none(),
        productId: value.productId,
        quantity: value.quantity,
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    productId?: ProductId;
    message: string;
    phone: string;
}): {
    name: string;
    productId: [] | [_ProductId];
    message: string;
    phone: string;
} {
    return {
        name: value.name,
        productId: value.productId ? candid_some(value.productId) : candid_none(),
        message: value.message,
        phone: value.phone
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
