/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProductInput = IDL.Record({
  'stockQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const ProductId = IDL.Nat;
export const InquiryId = IDL.Nat;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const IncomeStats = IDL.Record({
  'todayIncome' : IDL.Float64,
  'totalIncome' : IDL.Float64,
  'monthlyIncome' : IDL.Float64,
});
export const Inquiry = IDL.Record({
  'id' : InquiryId,
  'name' : IDL.Text,
  'productId' : IDL.Opt(ProductId),
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const ProductStatus = IDL.Variant({
  'inStock' : IDL.Null,
  'outOfStock' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'status' : ProductStatus,
  'stockQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'isHidden' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const SaleId = IDL.Nat;
export const Sale = IDL.Record({
  'id' : SaleId,
  'customerName' : IDL.Opt(IDL.Text),
  'productId' : ProductId,
  'productName' : IDL.Text,
  'pricePerUnit' : IDL.Float64,
  'totalAmount' : IDL.Float64,
  'quantity' : IDL.Nat,
  'phone' : IDL.Opt(IDL.Text),
  'saleDate' : IDL.Int,
});
export const SaleInput = IDL.Record({
  'customerName' : IDL.Opt(IDL.Text),
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'phone' : IDL.Opt(IDL.Text),
});
export const InquiryInput = IDL.Record({
  'name' : IDL.Text,
  'productId' : IDL.Opt(ProductId),
  'message' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProduct' : IDL.Func([ProductInput], [ProductId], []),
  'deleteInquiry' : IDL.Func([InquiryId], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getIncomeStats' : IDL.Func([], [IncomeStats], ['query']),
  'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getLowStockProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getMonthlyIncome' : IDL.Func([], [IDL.Float64], ['query']),
  'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([IDL.Bool], [IDL.Vec(Product)], ['query']),
  'getSalesByDate' : IDL.Func([IDL.Int], [IDL.Vec(Sale)], ['query']),
  'getSalesByMonth' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Sale)], ['query']),
  'getSalesByProduct' : IDL.Func([ProductId], [IDL.Vec(Sale)], ['query']),
  'getTodayIncome' : IDL.Func([], [IDL.Float64], ['query']),
  'getTotalIncome' : IDL.Func([], [IDL.Float64], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markInquiryRead' : IDL.Func([InquiryId], [], []),
  'recordSale' : IDL.Func([SaleInput], [SaleId], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setLowStockThreshold' : IDL.Func([IDL.Nat], [], []),
  'submitInquiry' : IDL.Func([InquiryInput], [InquiryId], []),
  'updateProduct' : IDL.Func([ProductId, ProductInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProductInput = IDL.Record({
    'stockQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const ProductId = IDL.Nat;
  const InquiryId = IDL.Nat;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const IncomeStats = IDL.Record({
    'todayIncome' : IDL.Float64,
    'totalIncome' : IDL.Float64,
    'monthlyIncome' : IDL.Float64,
  });
  const Inquiry = IDL.Record({
    'id' : InquiryId,
    'name' : IDL.Text,
    'productId' : IDL.Opt(ProductId),
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const ProductStatus = IDL.Variant({
    'inStock' : IDL.Null,
    'outOfStock' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'status' : ProductStatus,
    'stockQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'isHidden' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const SaleId = IDL.Nat;
  const Sale = IDL.Record({
    'id' : SaleId,
    'customerName' : IDL.Opt(IDL.Text),
    'productId' : ProductId,
    'productName' : IDL.Text,
    'pricePerUnit' : IDL.Float64,
    'totalAmount' : IDL.Float64,
    'quantity' : IDL.Nat,
    'phone' : IDL.Opt(IDL.Text),
    'saleDate' : IDL.Int,
  });
  const SaleInput = IDL.Record({
    'customerName' : IDL.Opt(IDL.Text),
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'phone' : IDL.Opt(IDL.Text),
  });
  const InquiryInput = IDL.Record({
    'name' : IDL.Text,
    'productId' : IDL.Opt(ProductId),
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProduct' : IDL.Func([ProductInput], [ProductId], []),
    'deleteInquiry' : IDL.Func([InquiryId], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getIncomeStats' : IDL.Func([], [IncomeStats], ['query']),
    'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getLowStockProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getMonthlyIncome' : IDL.Func([], [IDL.Float64], ['query']),
    'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([IDL.Bool], [IDL.Vec(Product)], ['query']),
    'getSalesByDate' : IDL.Func([IDL.Int], [IDL.Vec(Sale)], ['query']),
    'getSalesByMonth' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Sale)],
        ['query'],
      ),
    'getSalesByProduct' : IDL.Func([ProductId], [IDL.Vec(Sale)], ['query']),
    'getTodayIncome' : IDL.Func([], [IDL.Float64], ['query']),
    'getTotalIncome' : IDL.Func([], [IDL.Float64], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markInquiryRead' : IDL.Func([InquiryId], [], []),
    'recordSale' : IDL.Func([SaleInput], [SaleId], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setLowStockThreshold' : IDL.Func([IDL.Nat], [], []),
    'submitInquiry' : IDL.Func([InquiryInput], [InquiryId], []),
    'updateProduct' : IDL.Func([ProductId, ProductInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };