/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface IncomeStats {
  'todayIncome' : number,
  'totalIncome' : number,
  'monthlyIncome' : number,
}
export interface Inquiry {
  'id' : InquiryId,
  'name' : string,
  'productId' : [] | [ProductId],
  'isRead' : boolean,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export type InquiryId = bigint;
export interface InquiryInput {
  'name' : string,
  'productId' : [] | [ProductId],
  'message' : string,
  'phone' : string,
}
export interface Product {
  'id' : ProductId,
  'status' : ProductStatus,
  'stockQuantity' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'isHidden' : boolean,
  'category' : string,
  'price' : number,
}
export type ProductId = bigint;
export interface ProductInput {
  'stockQuantity' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : number,
}
export type ProductStatus = { 'inStock' : null } |
  { 'outOfStock' : null };
export interface Sale {
  'id' : SaleId,
  'customerName' : [] | [string],
  'productId' : ProductId,
  'productName' : string,
  'pricePerUnit' : number,
  'totalAmount' : number,
  'quantity' : bigint,
  'phone' : [] | [string],
  'saleDate' : bigint,
}
export type SaleId = bigint;
export interface SaleInput {
  'customerName' : [] | [string],
  'productId' : ProductId,
  'quantity' : bigint,
  'phone' : [] | [string],
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProduct' : ActorMethod<[ProductInput], ProductId>,
  'deleteInquiry' : ActorMethod<[InquiryId], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getIncomeStats' : ActorMethod<[], IncomeStats>,
  'getInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getLowStockProducts' : ActorMethod<[], Array<Product>>,
  'getMonthlyIncome' : ActorMethod<[], number>,
  'getProductById' : ActorMethod<[ProductId], [] | [Product]>,
  'getProducts' : ActorMethod<[boolean], Array<Product>>,
  'getSalesByDate' : ActorMethod<[bigint], Array<Sale>>,
  'getSalesByMonth' : ActorMethod<[bigint, bigint], Array<Sale>>,
  'getSalesByProduct' : ActorMethod<[ProductId], Array<Sale>>,
  'getTodayIncome' : ActorMethod<[], number>,
  'getTotalIncome' : ActorMethod<[], number>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markInquiryRead' : ActorMethod<[InquiryId], undefined>,
  'recordSale' : ActorMethod<[SaleInput], SaleId>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setLowStockThreshold' : ActorMethod<[bigint], undefined>,
  'submitInquiry' : ActorMethod<[InquiryInput], InquiryId>,
  'updateProduct' : ActorMethod<[ProductId, ProductInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];